application_name: sample-api
business_unit: Funds
Variables:
  owner_email: platform-team@example.com
Environments:
  - name: Dev
    publisherDomain: contoso-dev.onmicrosoft.com
    tenancy_type: workforce
    environment_code: dev
  - name: Prod
    publisherDomain: contoso.onmicrosoft.com
    tenancy_type: workforce
    environment_code: prod
Dependencies: {}
